#
# Copyright (C) 2024 The Android Open Source Project
# Copyright (C) 2024 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/alps/pocketalk
BOARD_VENDOR := alps
BOARD_DEVICE := pocketalk
ALLOW_MISSING_DEPENDENCIES := true

BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
BOARD_SUPPRESS_SECURE_ERASE := true

TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

# mtk
BOARD_HAS_MTK_HARDWARE := true
BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE := true 

TARGET_USES_64_BIT_BINDER := true
TARGET_SUPPORTS_32_BIT_APPS := true
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_VARIANT_RUNTIME := generic
TARGET_2ND_ARCH :=
TARGET_2ND_ARCH_VARIANT :=
TARGET_2ND_CPU_ABI :=
TARGET_2ND_CPU_ABI2 :=
TARGET_2ND_CPU_VARIANT :=
TARGET_2ND_CPU_VARIANT_RUNTIME :=
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_CPU_ABI),$(TARGET_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_32_BIT)

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := k39tv1_bsp
TARGET_BOARD_PLATFORM := mt6739
TARGET_NO_FACTORYIMAGE:=true
TARGET_NO_BOOTLOADER := true
TARGET_USES_UEFI := true

# Display
TARGET_SCREEN_DENSITY := 120
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 120


# Kernel
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_CMDLIN += bootopt=64S3,32S1,32S1
BOARD_KERNEL_CMDLIN += androidboot.selinux=permissive
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x05000000
BOARD_SECOND_OFFSET := 0x00f00000
BOARD_KERNEL_TAGS_OFFSET := 0x04000000
BOARD_HASH_TYPE := sha1
BOARD_HEADER_VERSION := 0
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)

BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_HEADER_ARCH := arm

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
endif

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 25165824 
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 25165824
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2684354560
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_PARTITION_SIZE := 578813952
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USES_MKE2FS := true

TARGET_COPY_OUT_VENDOR := vendor

# Recovery
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBA_8888"
RECOVERY_SDCARD_ON_DATA := true

# Security patch level
VENDOR_SECURITY_PATCH := 2018-07-05

# Hack: prevent anti rollback
PLATFORM_SECURITY_PATCH := 2018-07-05
VENDOR_SECURITY_PATCH := 2018-07-05
PLATFORM_VERSION := 8

TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := false
BOARD_USES_METADATA_PARTITION := true
BOARD_METADATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VNDK_VERSION := current

# TWRP Configuration
TW_THEME := portrait_mdpi
TW_EXTRA_LANGUAGES := false
TW_USE_INPUT_EVENTS := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_SCREEN_BLANK_ON_BOOT := true
# TW_NO_SCREEN_TIMEOUT := true
TW_USE_TOOLBOX := true
TW_EXCLUDE_BASH := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_LZMA := true
TW_EXCLUDE_SED := true
TW_EXCLUDE_TAR := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_PYTHON := true
TW_NO_EXFAT_FUSE := false
TW_NO_BZIP2 := true
TW_DEFAULT_LANGUAGE := en
TW_EXCLUDE_GZIP := false
TW_EXCLUDE_XZ := true
#PRODUCT_SOONG_NAMESPACES += $(DEVICE_PATH)
